---
title: "doubleslit"
author: "Kevin Robb"
date: "9/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval=FALSE}
#create fake data
set.seed(23)
#Generate x as 100 integers using seq function
x<-seq(0,100,1)
y<-runif(1,0,20)*exp(runif(1,0.005,0.075)*x)+runif(101,0,5)
plot(x,y)
```

```{r readdata_dslaser}
#read in actual data
#getwd()
dslaser = read.csv("aug29_ds_laser.csv")
#head(dslaser)
plot(Voltage~Position,data=dslaser,pch=21,bg="black",xlim=c(2,9),ylim=c(0,2.5),cex=1.2,ylab="Intensity (V)",xlab="Detector Slit Position (mm)")
```


```{r eval=FALSE}
#Linear model
  
lin_mod=lm(dslaser$Voltage~dslaser$Position)

#Plotting the model

plot(dslaser$Position,dslaser$Voltage)

abline(lin_mod)

#There is little overlap between the actual values and the fitted plot. Now let’s try the nonlinear model and specify the formula
```


$$\alpha = \frac{\pi a}{\lambda} \sin \theta \textrm{ and } \beta = \frac{\pi d}{\lambda} \sin \theta \textrm{ .}$$

$$\textrm{where } \sin\theta = \frac{L}{\sqrt{{\Delta x}^2+L^2}} \\ \theta = \pi - \frac{x-x_0}{L}$$

$$I_2(\theta) = I_0 \left( \frac{\sin \alpha}{\alpha} \right)^2 \cos^2 \beta \textrm{ .} $$

$$I_1(\theta) = \frac{I_0}{4} \left( \frac{\sin \alpha}{\alpha} \right)^2 \textrm{ .} $$

```{r testfitfunction eval=FALSE}
#nonlinear model
#nonlin_mod=nls(y~a*exp(b*x),start=list(a=13,b=0.1)) #a is the starting value and b is the exponential start
y = dslaser$Voltage
x = dslaser$Position
#starting guesses
x0 = 5.35 #central max position
I0=2.8
alam=0.1/0.00067
dlam=0.457/0.00067
#darkcount=70
#simplification (not valid)
#sinangle = 500/sqrt(500^2+(x-x0)^2)
sinangle = (x-x0)/sqrt(500^2+(x-x0)^2)
#head(sinangle)

plot(x,y)
#x<-seq(0,100,0.1)
plot(x,I0*(sin(pi*alam*(x-x0)/sqrt(500^2+(x-x0)^2))/(pi*alam*(x-x0)/sqrt(500^2+(x-x0)^2)))^2*(cos(pi*dlam*(x-x0)/sqrt(500^2+(x-x0)^2)))^2, ylab="Intensity Prediction")
plot(x,I0*(sin(pi*alam*(500)/sqrt(500^2+(x-x0)^2))/(pi*alam*(500)/sqrt(500^2+(x-x0)^2)))^2*(cos(pi*dlam*(500)/sqrt(500^2+(x-x0)^2)))^2, ylab="Intensity Prediction")


x<-seq(2.8,8.8,0.01)
theta = pi - (x - x0)/500
plot(x,I0*(sin(pi*alam*sin(theta))/(pi*alam*sin(theta)))^2 * (cos(pi*dlam*sin(theta)))^2, ylab="Intensity Prediction", col="blue")
```

```{r testerrorbars eval=FALSE}
plot(x, avg,
    ylim=range(c(avg-sdev, avg+sdev)),
    pch=19, xlab="Measurements", ylab="Mean +/- SD",
    main="Scatter plot with std.dev error bars"
)
# hack: we draw arrows but with very special "arrowheads"
arrows(x, avg-sdev, x, avg+sdev, length=0.05, angle=90, code=3)
```

```{r plotfitfunction_no_nls eval=FALSE}
#get the data set to x and y for convenience
y = dslaser$Voltage
x = dslaser$Position

#initial guesses
lambda0 = 0.000658 #guess for lambda from approximations
x0 = 5.33 #central max position
I0=2.083
a=0.101
d=0.457
lambda=0.00067
darkcount=0.1 #very small for multimeter

#theta = pi - (x - x0)/500
plot(x,y,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
#error bars are arrows with special arrowheads
arrows(x, y-0.05, x, y+0.05, length=0.05, angle=90, code=3)


x<-seq(2.8,8.8,0.001)
lines(x,I0*(sin(pi*a/lambda*sin(pi - (x - x0)/500))/(pi*a/lambda*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda*sin(pi - (x - x0)/500)))^2 + darkcount, col="blue")

```

```{r nonlinfit_v1 eval=FALSE}
#get data
ydata = dslaser$Voltage
xdata = dslaser$Position
y = ydata
lambda0 = 0.000658 #guess for lambda from approximations

#laser double slit. no dark count offset needed
#all lengths measured in mm
x<-seq(2.8,8.8,0.1)
fraun=nls(y~I0*(sin(pi*a/lambda0*sin(pi - (x - x0)/500))/(pi*a/lambda0*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda0*sin(pi - (x - x0)/500)))^2, start=list(I0=2.070, a=0.1, d=0.457, x0=5.35))

summary(fraun)
#1 - sqrt(0.129) = r
#This new plot can be made by using the lines() function
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
lines(x,predict(fraun),col="red") #actual prediction

#set parameters from fit summary
x0 = 5.3354
I0 = 2.15206
a = 0.085
d = 0.447
lambda=0.000658

xcalc<-seq(2.8,8.8,0.01) #NEED TO INCREASE DENSITY BUT CAN'T
#ycalc = I0*(sin(pi*a/lambda*sin(pi - (x - x0)/500))/(pi*a/lambda*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda0*sin(pi - (x - x0)/500)))^2

#plot from parameters
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
lines(xcalc,I0*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 * (cos(pi*d/lambda*sin(pi - (xcalc - x0)/500)))^2,col="blue")

#Error calculation

error <- lin_mod$residuals  

lm_error <- sqrt(mean(error^2))   #5.960544

error2=y-predict(nonlin_mod)

nlm_error <- sqrt(mean(error2^2)) #1.527064
```

```{r nonlinfit_vertshift_savefig3}
#get data
ydata = dslaser$Voltage
xdata = dslaser$Position
y = ydata
lambda0 = 0.000658 #guess for lambda from approximations

x<-seq(2.8,8.8,0.1)
fraun=nls(y~I0*(sin(pi*a/lambda0*sin(pi - (x - x0)/500))/(pi*a/lambda0*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda0*sin(pi - (x - x0)/500)))^2 + darkcount, start=list(I0=2.070, a=0.1, d=0.457, x0=5.35, darkcount=0.1))

summary(fraun)
#1 - sqrt(0.129) = r
#This new plot can be made by using the lines() function
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
lines(x,predict(fraun),col="red") #actual prediction

#set parameters from fit summary
darkcount = 0.177812
x0 = 5.335782
I0 = 1.945001 #(add darkcount for measured I0)
a = 0.094913
d = 0.447712
lambda=0.000658

xcalc<-seq(2.8,8.8,0.01) #NEED TO INCREASE DENSITY BUT CAN'T
#ycalc = I0*(sin(pi*a/lambda*sin(pi - (x - x0)/500))/(pi*a/lambda*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda0*sin(pi - (x - x0)/500)))^2

#plot from parameters and save to png
#png("figure3.png", width=500, height=350) #open the file
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
#error bars
arrows(x, y-0.05, x, y+0.05, length=0.05, angle=90, code=3)
lines(xcalc,I0*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 * (cos(pi*d/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="blue")
#dev.off() #close the file
```


```{r test_savepngfig3 eval=FALSE}
#read in the data
dslaser = read.csv("aug29_ds_laser.csv")
#get the data set to x and y for convenience
y = dslaser$Voltage
x = dslaser$Position
xcalc<-seq(2.8,8.8,0.001)

#fitting parameters
lambda0 = 0.000658
x0 = 5.33
I0=2.083
a=0.101
d=0.457
lambda=0.00067
darkcount=0.1 #very small for multimeter
#theta = pi - (x - x0)/500


## 1. Open png file
png("figure3.png") #, width = 350, height = "350"

## 2. Create the plot
# plot data points
plot(x,y,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (V)", col="black",pch=16,cex=1.1, ylim=c(0,2.5))
# error bars are arrows with special arrowheads
arrows(x, y-0.05, x, y+0.05, length=0.05, angle=90, code=3)
# plot fitting function
lines(xcalc,I0*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 * (cos(pi*d/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount, col="blue")

## 3. Close the file
dev.off()
```


```{r dsbulb_fig4}
#get data
dsbulb=read.csv("sep04_ds_bulb.csv")
xdata = dsbulb$Position
ydata = dsbulb$AvgCount #counts per second = intensity
y = ydata
lambda0 = 0.000594 #guess for lambda from approximations

x<-seq(2.8,8.8,0.1)
fraun=nls(y~I0*(sin(pi*a/lambda0*sin(pi - (x - x0)/500))/(pi*a/lambda0*sin(pi - (x - x0)/500)))^2 * (cos(pi*d/lambda0*sin(pi - (x - x0)/500)))^2 + darkcount, start=list(I0=251.5, a=0.1, d=0.457, x0=5.35, darkcount=70))

summary(fraun)
#1 - sqrt(0.129) = r
#This new plot can be made by using the lines() function
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (Counts per Second)", col="black",pch=16,cex=1.1, ylim=c(0,260))
lines(x,predict(fraun),col="red") #actual prediction

#set parameters from fit summary
darkcount = 91.38
x0 = 5.361
I0 = 168.9 #(add darkcount for measured I0)
a = 0.102
d = 0.4803
lambda=0.000594

xcalc<-seq(2.8,8.8,0.01)

#plot from parameters and save to png
#png("figure4.png", width=500, height=350) #open the file
plot(xdata,ydata,xlab="Detector Slit Position (mm)",ylab="Intensity Prediction (Counts Per Second)", col="black",pch=16,cex=1.1, ylim=c(70,260))
#error bars
arrows(x, y-5.133, x, y+5.133, length=0.05, angle=90, code=3)
lines(xcalc,I0*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 * (cos(pi*d/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="blue")
#dev.off() #close the file
```

```{r ssbulb_fig5}
#get data
fsbulb=read.csv("sep05_fs_bulb9.csv")
x_fs=fsbulb$Position
y_fs=fsbulb$AvgCount
nsbulb=read.csv("sep09_ns_bulb.csv")
x_ns=nsbulb$Position
y_ns=nsbulb$AvgCount

lambda0 = 0.000594 #guess for lambda from approximations

# fit far slit data
x = x_fs
y = y_fs

x<-seq(2.8,8.8,0.1)
fraun_fs=nls(y~I0/4*(sin(pi*a/lambda0*sin(pi - (x - x0)/500))/(pi*a/lambda0*sin(pi - (x - x0)/500)))^2 + darkcount, start=list(I0=2432.5, a=0.1, x0=5.0, darkcount=70))
summary(fraun_fs)
#1 - sqrt(0.129) = r
#This new plot can be made by using the lines() function
#plot(x_fs,y_fs,xlab="Detector Slit Position (mm)",ylab="Intensity (Counts per Second)", col="black",pch=16,cex=1.1, ylim=c(0,500))
#lines(x,predict(fraun_fs),col="red")

#set parameters from fit summary
darkcount = summary(fraun_fs)$coefficients[4,1]
x0 = summary(fraun_fs)$coefficients[3,1]
I0 = summary(fraun_fs)$coefficients[1,1] #(add darkcount for measured I0)
I_error = summary(fraun_fs)$coefficients[1,2]
a = summary(fraun_fs)$coefficients[2,1]
lambda=0.000594

#plot far slit only
xcalc<-seq(2.8,8.8,0.01)
#png("figure4.png", width=500, height=350) #open the file
plot(x_fs,y_fs,xlab="Detector Slit Position (mm)",ylab="Intensity (Counts Per Second)", col="black",pch=16,cex=1.1, ylim=c(50,500))
#error bars
arrows(x, y-I_error, x, y+I_error, length=0.05, angle=90, code=3)
lines(xcalc,I0/4*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="blue")
#dev.off() #close the file

#--------------------------------------------------------------------
# fit near slit data
x = x_ns
y = y_ns
x<-seq(2.8,8.8,0.1)
fraun_ns=nls(y~I0/4*(sin(pi*a/lambda0*sin(pi - (x - x0)/500))/(pi*a/lambda0*sin(pi - (x - x0)/500)))^2 + darkcount, start=list(I0=2432.5, a=0.1, x0=5.0, darkcount=70))
summary(fraun_ns)

#set parameters from fit summary
darkcount = summary(fraun_ns)$coefficients[4,1]
x0 = summary(fraun_ns)$coefficients[3,1]
I0 = summary(fraun_ns)$coefficients[1,1] #(add darkcount for measured I0)
I_error = summary(fraun_ns)$coefficients[1,2]
a = summary(fraun_ns)$coefficients[2,1]
lambda=0.000594

#plot near slit only
xcalc<-seq(2.8,8.8,0.01)
#png("figure4.png", width=500, height=350) #open the file
plot(x_ns,y_ns,xlab="Detector Slit Position (mm)",ylab="Intensity (Counts Per Second)", col="black",pch=16,cex=1.1, ylim=c(50,1000))
#error bars
arrows(x_ns, y_ns-I_error, x_ns, y_ns+I_error, length=0.05, angle=90, code=3)
lines(xcalc,I0/4*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="blue")
#dev.off() #close the file

#---------------------------------------------------------------------------
#plot both on same graph

#png("figure5.png", width=500, height=350) #open the file

xcalc<-seq(2.8,8.8,0.01) #fitting function density
# set far slit parameters
darkcount = summary(fraun_fs)$coefficients[4,1]
x0 = summary(fraun_fs)$coefficients[3,1]
I0 = summary(fraun_fs)$coefficients[1,1] #(add darkcount for measured I0)
I_error = summary(fraun_fs)$coefficients[1,2]
a = summary(fraun_fs)$coefficients[2,1]

#start plot with far slit points
plot(x_fs,y_fs,xlab="Detector Slit Position (mm)",ylab="Intensity (Counts Per Second)", col="red",pch=16,cex=1.1, ylim=c(50,1000))
# far slit error bars
arrows(x_fs, y_fs-I_error, x_fs, y_fs+I_error, length=0.05, angle=90, code=3)
# plot far slit fitting function
lines(xcalc,I0/4*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="red")

# set near slit parameters
darkcount = summary(fraun_ns)$coefficients[4,1]
x0 = summary(fraun_ns)$coefficients[3,1]
I0 = summary(fraun_ns)$coefficients[1,1] #(add darkcount for measured I0)
I_error = summary(fraun_ns)$coefficients[1,2]
a = summary(fraun_ns)$coefficients[2,1]

# add near slit points and error bars
points(x_ns,y_ns, col="blue",cex=1.1) #pch=16
# near slit error bars
arrows(x_ns, y_ns-I_error, x_ns, y_ns+I_error, length=0.05, angle=90, code=3)
# plot near slit fitting function
lines(xcalc,I0/4*(sin(pi*a/lambda*sin(pi - (xcalc - x0)/500))/(pi*a/lambda*sin(pi - (xcalc - x0)/500)))^2 + darkcount,col="blue")

#add legend to plot
legend("topleft", legend=c("Far Slit Only", "Near Slit Only"), col=c("red", "blue"), pch = c(16,1), cex=1.2) #lty=1:2

#dev.off() #close the file
```
